# @url=http://dokkuweb.credot.ml
@url=http://localhost:8081
@appName=amber2

#####
GET {{url}}/api/test

########
GET {{url}}/api/version


#####
GET {{url}}/api/redirect

#######
POST {{url}}/api/account/login
Content-Type: application/json

{
    "account":"admin",
    "password":"1qaz#EDC5tgb"
}

######
GET {{url}}/api/ssh/check

############
POST {{url}}/api/account/logout

########
GET {{url}}/api/logs/{{appName}}/10

######### Apps ########
GET {{url}}/api/apps

#########
GET {{url}}/api/app/{{appName}}

########
POST {{url}}/api/app/{{appName}}

######## Git #########
GET {{url}}/api/git/{{appName}}

######
POST {{url}}/api/git/{{appName}}

######## Proxy #########
GET {{url}}/api/proxy/{{appName}}

########
PATCH {{url}}/api/proxy/{{appName}}/enable

########
PATCH {{url}}/api/proxy/{{appName}}/disable

#####
PATCH {{url}}/api/proxy/{{appName}}
Content-Type: application/json

{"scheme": "http", "hostPort":"80","containerPort":"1234"}

#####
DELETE {{url}}/api/proxy/{{appName}}
Content-Type: application/json

{"scheme": "http", "hostPort":"80","containerPort":"1234"}

####### Domain ########
GET {{url}}/api/domain/{{appName}}

################################
PATCH {{url}}/api/domain/{{appName}}/enable

################################
PATCH {{url}}/api/domain/{{appName}}/disable

################################
PATCH {{url}}/api/domain/{{appName}}
Content-Type: application/json

["temp.credot.ml","test.credot.ml"]

################################
DELETE  {{url}}/api/domain/{{appName}}
Content-Type: application/json

["temp.credot.ml","test.credot.ml"]
###########
GET {{url}}/api/globaldomain

###########
PUT {{url}}/api/globaldomain
Content-Type: application/json

["dokku.credot.ml"]

###########
DELETE {{url}}/api/globaldomain

######## Config #######
GET {{url}}/api/config/{{appName}}

##########
POST {{url}}/api/config/{{appName}}
Content-Type: application/json

{
    "restart":true,
    "config":[{"key":"key","value":"v1"},{"key":"ke2y","value":"v2"}]
}

#########
DELETE  {{url}}/api/config/{{appName}}

#########
GET  {{url}}/api/globalconfig
#######

########   Database

########
GET {{url}}/api/databases

#########
POST {{url}}/api/database/postgres

########
PATCH {{url}}/api/database/postgres/enable

#####3
PATCH {{url}}/api/database/postgres/disable

########
DELETE  {{url}}/api/database/postgres

#######

########   Database Service

#######
GET {{url}}/api/dbservice/postgres

######
GET {{url}}/api/dbservice/postgres/test2

#####
POST {{url}}/api/dbservice/postgres
Content-Type: application/json

{
    "service":"test2",
    "password":"123456",
    "rootPassword":"1qaz#EDC5tgb"
}

######
PATCH {{url}}/api/dbservice
Content-Type: application/json

{
    "database":"postgres",
    "service":"test2",
    "start":"stop"
}

######
GET {{url}}/api/dblinks/postgres/test

######
POST {{url}}/api/dblink
Content-Type: application/json

{
    "database":"postgres",
    "service":"test2",
    "appName":"adminer",
    "link":false
}

## dokku-postgres-test2
####
POST https://api.cloudflare.com/client/v4/zones/2df42beb73d51f4d041a063e23eb96c9/dns_records
Authorization:Bearer TeFsU6Y1sbK22PrnkqhoU3sUsAAYn-Pt8I-FrzP9
Content-Type:application/json

{"type":"A","name":"admintest","content":"34.81.157.108","ttl":1,"proxied":true}